### ISSUE TITLE
A swiss army knife for Unist-util-*.

### ISSUE THREAD

**Issue by Rokt33r** [syntax-tree/unist#11]
![swiss army knife](https://upload.wikimedia.org/wikipedia/commons/c/cb/Swiss_army_knife_open_20050612_(cropped).jpg)

Just like lodash, I need an object bound every `unist-util-*` methods.
It might be a bad practice for the production code. But, for testing code, I think it would be fine.

Also, I need others for `hast-util-*` and `mdast-util-*` too...

What do you think?

**Comment by anko** [comment]
```javascript
var unistUtil = {}
;[
    "assert",
    "filter",
    "find",
    "find-after",
    "find-all-after",
    "find-all-before",
    "find-all-between",
    "find-before",
    "generated",
    "index",
    "inspect",
    "is",
    "map",
    "modify-children",
    "parents",
    "position",
    "remove",
    "remove-position",
    "select",
    "source",
    "stringify-position",
    "visit",
    "visit-parents",
    "visit-children"
].forEach((name) => unistUtil[name] = require("unist-util-" + name))
```

:white_check_mark:

**Comment by Rokt33r** [comment]
I don't think your answer is the best. I still have to install all of them with `npm install`. Also, it will pollute my `devDependencies`.

Btw, to answer your question, I think most of newbies doesn't notice that these great tools exist because the tools are too scattered.

The knife would make people can toy this project much easier. They shouldn't be bothered to check every projects of the each method.
Also, I think using the separated modules is needed to optimize just for the production level.

**Comment by Rokt33r** [comment]
Anyway, I also understand it might be annoying to maintain... Thanks for your opinion.

**Comment by wooorm** [comment]
My biggest thing is that it’ll be so bad for production. If it exists, I feel people will mistakingly start depending on it.

However, feel free to create this if you want to. That’s totally okay!

> I think most of newbies doesn't notice that these great tools exist because the tools are too scattered.

If that’s the problem, than we should fix that! (And I don’t think bundling the utilities does that)
This sounds like a documentation problem. And the docs aren’t very good now. I’d like to make them better for newcomers. Do you have any suggestion on making them better?

> Also, it will pollute my `devDependencies`.

You can also use something like [RunKit](https://runkit.com/npm/unist-util-visit) to try things out!

**Comment by Rokt33r** [comment]
I agree. More documents would be better. Thanks for sharing RunKit. It seems to be very useful.
