### ISSUE TITLE
unist-util-visit

### ISSUE THREAD

**Issue by deuxego** [syntax-tree/unist#139]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=issues) and [discussions](https://github.com/orgs/syntax-tree/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

unist-util-visit

### Steps to reproduce

https://www.npmjs.com/package/unist-util-visit

package 'unist-util-visit' not found

### Actual behavior

not found

### Expected behavior

found

**Comment by remcohaszing** [comment]
It exists. I read something about an npm outage today. That mighy have been the issue.
