### ISSUE TITLE
No utility for creating a selector from a root and a leaf node.

### ISSUE THREAD

**Issue by lifeiscontent** [syntax-tree/unist#14]
@wooorm is there a utility to build a selector if you pass it a root and a leaf node?

e.g. `buildSelector(root, node); // returns 'html > body > div:nth-child(1) > h1'`

I'm creating a tree component that displays the AST and when you click on a node, it `selects` the selected nodes of the AST. and I'm wondering how to create the selector needed for the select util.

**Comment by wooorm** [comment]
Nice! Nope, not yet! You could open an issue in the [`ideas`](https://github.com/syntax-tree/ideas) repo for new utility ideas (whether or not you’d like to work on it!)

Plus that sounds 👍 Let me know by discussing there if you need help, and how I can help!
