### ISSUE TITLE
Specify `indent`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/unist#16]
`node.position.indent` isn’t used a lot, but it could be specced better.

Currently, it’s a list of integers, if a node spans multiple lines, where each value refers to the column a line (`node.position.start.line + index`).
This only supports the start of a line (which is useful in markdown). But not the end of a line.
It’s also awkward to access, as there’s no explicit line access.

It could make sense for `indent` to be an `Array.<{start: Point, end: Point}>`.

**Comment by unicornware** [comment]
for those wanting to implementing their own ast, can this be revisited? or can the `README` be updated to include an example?

**Comment by wooorm** [comment]
Hm I think it should be removed from the spec instead now that it isn’t used anymore.
You probably shouldn’t implement it?

`indent` is useful for things that span multiple lines, and start at different “columns”. Which can occur in markdown.

So say something spans 3 lines, then `position.start` is the starting point.
`indent[0]` is the column of line 2, `indent[1] the column of line 3.
