### ISSUE TITLE
Rename abstract “text” interface to “literal”

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/unist#17]
The abstract text interface (nodes with a `value`) interferes with the `type: "text"` node provided by hast and mdast (and the `type: "TextNode"` provided by nlcst).

Another downside is that `text` implies (and specifies) `string` values on the `value` field.
Say unist was used for programming values, the value of `value` could be specified as `number`, for example.

I’m open to other names, but I’m searching for something close to “raw”, “leaf”, and whatnot.

/CC @ChristianMurphy What do you think?

**Comment by ChristianMurphy** [comment]
Seems like a good direction to take, replacing `Text` with something more flexible.
I'd lean a bit toward `Literal`, `Raw` may conflict in some configuration type languages where there are template literals and raw literals.
I know groovy-like configuration languages distinguish between `"text with ${template}"` and `'raw text'`

**Comment by wooorm** [comment]
@ChristianMurphy Thanks, I totes agree!

Leaf was another thing I thought of, but that would prohibit the use of something that has both a value and children in the future (and a node without value or children could also be a “leaf”, as a concept).
