### ISSUE TITLE
Error at C:/web/node_modules/@types/unist/index.d.ts:92:58: ';' expected.

### ISSUE THREAD

**Issue by mohamedumer** [syntax-tree/unist#47]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@types/unist & 2.0.6

### Steps to reproduce

angular - 4.3.6
node- 10.15.0
react-markdown- 4.0.3
 with above version if we try to build angular app, we are getting below error.
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/53818424/125787400-fdd1b118-c044-42cb-a5d0-44d1c9abebdb.png)

### Expected behavior

it should build the app.

### Actual behavior

due to @types/unist package issue we wont be able to build angular app.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

yarn v1

### OS

Windows, Linux

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
Testing this out with Angular 11 this doesn't appear to be an issue https://codesandbox.io/s/angular-11-example-ssg15
Could you try upgrading the TypeScript version you are using? `unist` and most of `unified` and `remark` currently support TypeScript version 3 or higher. In the next major release TypeScript 4 and higher.
The error you as seeing looks like a TypeScript version 2 error.

**Comment by ChristianMurphy** [comment]
This works on supported versions of Angular (https://angular.io/guide/releases#support-policy-and-schedule) and supported versions of TypeScript, version 3+.

**Comment by mohamedumer** [comment]
We tried to upgrade Typescript greater than 3. but getting error while running **yarn install**, so we checked out with **Ts 2.9.2** then the build is fine in local. where in pipeline still we are facing issue with the app build, which takes longer time, eventually getting failed. is there anything to consider apart from Typescript upgrade.

**Comment by ChristianMurphy** [comment]
A TypeScript upgrade to version 3 or higher is the more consistent and likely way to get it to work.

You could try pinning older versions of types packages that are failing, so see if they work with legacy typescript.
Or you could manually edit typings with https://github.com/ds300/patch-package#readme to remove features until it works with legacy typescript versions.
